name: Scala CI

on:
  push:
    branches: [ cleaned, master, main ]
  pull_request:
    branches: [ cleaned, master, main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Scala Code Format
          run:|
            chmod +x ./scalafmt
            ./scalafmt --list
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run tests
        run: sbt multi-jvm:test
